# multiply datasource
spring:
  datasource:
    ds1: #数据源1
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://ip:3306/jepaas?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: root
      password: bt5
    ds2: # 数据源2
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://ip:1433;DatabaseName=poweron
      username: weaver
      password: SIDRIweave

